import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "en" | "th" | "zh" | "ja" | "ko";

interface LanguageOption {
  code: Language;
  name: string;
  nativeName: string;
  flag: string;
}

export const languages: LanguageOption[] = [
  { code: "en", name: "English", nativeName: "English", flag: "🇬🇧" },
  { code: "th", name: "Thai", nativeName: "ไทย", flag: "🇹🇭" },
  { code: "zh", name: "Chinese", nativeName: "中文", flag: "🇨🇳" },
  { code: "ja", name: "Japanese", nativeName: "日本語", flag: "🇯🇵" },
  { code: "ko", name: "Korean", nativeName: "한국어", flag: "🇰🇷" },
];

// Translations for common UI elements
export const translations: Record<Language, Record<string, string>> = {
  en: {
    chat: "Chat",
    itinerary: "Itinerary",
    landmark: "Landmarks",
    polaroid: "Polaroid",
    profile: "Profile",
    help: "Help & Support",
    signOut: "Sign Out",
    newChat: "New Chat",
    searchPlaceholder: "Search landmarks...",
    startNavigation: "Start Navigation",
    pause: "Pause",
    walk: "Walk",
    drive: "Drive",
    transit: "Transit",
    showSteps: "Show Steps",
    hideSteps: "Hide Steps",
    locateMe: "Find my location",
    arrived: "You've arrived!",
    welcomeTo: "Welcome to",
    routeError: "Could not calculate route",
    locationFound: "Location found",
    usingCurrentLocation: "Using your current location",
    findRestaurant: "Find me a restaurant",
    cheapEats: "Best cheap eats nearby",
    premiumSeafood: "Premium seafood",
    spicyFood: "Something spicy",
    lateNightFood: "Late night food",
    minWait: "min wait",
    viewOnMap: "View on Map",
    directions: "Directions",
    all: "All",
    highestRated: "Highest Rated",
    mostReviews: "Most Reviews",
    landmarksFound: "landmarks found",
    bestTime: "Best",
    estimatedTime: "~",
    modes: "MODES",
    recentChats: "RECENT CHATS",
    noRecentChats: "No recent chats available",
    pressNewChat: "Press \"+ New Chat\" to start!",
    deleteChat: "Delete this chat?",
    deleteChatDesc: "This action cannot be undone. This will permanently delete this chat session and all its messages.",
    cancel: "Cancel",
    delete: "Delete",
    startConversation: "Start a Conversation",
    startConversationDesc: "Ask me about restaurants, queue times, or local recommendations!",
    planAdventure: "Plan Your Adventure",
    planAdventureDesc: "Tell me your budget and interests, and I'll create the perfect itinerary.",
    discoverLandmarks: "Discover Landmarks",
    discoverLandmarksDesc: "Find Instagram-worthy spots and hidden gems in Bantadthong.",
    createPolaroids: "Create Polaroids",
    createPolaroidsDesc: "Upload your photos and I'll transform them into beautiful polaroids.",
    messagePlaceholder: "Message .Hubb...",
    bantadthongDistrict: "Bantadthong District",
    listening: "Listening...",
    active: "Active",
    chatMode: "Chat",
    itineraryMode: "Itinerary Mode",
    landmarkMode: "Landmarks Mode",
    polaroidMode: "Polaroid Mode",
    today: "Today",
    yesterday: "Yesterday",
    daysAgo: "days ago",
    new: "New",
    noLandmarksFound: "No landmarks found matching your criteria.",
    university: "University",
    shopping: "Shopping",
    museum: "Museum",
    temple: "Temple",
    park: "Park",
    market: "Market",
    // Prompt suggestions
    findRestaurantNoWait: "Find me a restaurant with no wait",
    bestCheapEats: "Best cheap eats nearby",
    somethingSpicy: "Something spicy",
    // Toast notifications
    locationNotSupported: "Location not supported",
    browserNoGeolocation: "Your browser doesn't support geolocation. Using Bantadthong center.",
    locationFoundTitle: "📍 Location found",
    accuracyLabel: "Accuracy",
    locationOutsideBantadthong: "Location outside Bantadthong",
    usingBantadthongCenter: "Using Bantadthong center as your location",
    couldNotGetLocation: "Could not get location",
    enableLocationAccess: "Using Bantadthong center. Please enable location access.",
    liveTrackingEnabled: "🔴 Live tracking enabled",
    locationWillUpdate: "Your location will update in real-time",
    youveArrived: "🎉 You've arrived!",
    gpsError: "GPS error",
    couldNotUpdateLocation: "Could not update location. Retrying...",
    liveTrackingStopped: "Live tracking stopped",
    locationNoLongerTracked: "Your location is no longer being tracked",
    // Review notifications
    justReviewed: "just reviewed",
    justVisited: "just visited",
    minutesAgo: "min ago",
    leftReviewAt: "left a review at",
    justNow: "just now",
    // Itinerary
    itineraryPlanner: "Itinerary Planner 🗺️",
    planBantadthongTour: "Plan your perfect Bantadthong food tour",
    budgetLevel: "Budget Level",
    budgetLow: "฿ Budget",
    budgetMid: "฿฿ Mid",
    budgetHigh: "฿฿฿ Premium",
    underPrice: "Under 400 THB",
    midPrice: "400-700 THB",
    highPrice: "700+ THB",
    numberOfPlaces: "Number of Places",
    cuisinePreference: "Cuisine Preference",
    anyCuisine: "Any Cuisine",
    generateItinerary: "Generate Itinerary",
    estBudget: "Est. Budget",
    totalWait: "Total Wait",
    stops: "Stops",
    editPreferences: "Edit Preferences",
    // Polaroid
    polaroidModeTitle: "Polaroid Mode 📸",
    transformMemories: "Transform your Bantadthong memories into vintage polaroids",
    uploadPhoto: "Upload a photo",
    clickOrDrag: "Click or drag and drop",
    createPolaroidBtn: "Create Polaroid",
    creating: "Creating...",
    download: "Download",
    polaroidCreated: "Polaroid created! 📸",
    photoTransformed: "Your photo has been transformed into a polaroid.",
    downloaded: "Downloaded!",
    polaroidSaved: "Your polaroid has been saved.",
    // Auth & Logout
    signedOut: "Signed out",
    seeYouNextTime: "See you next time!",
    welcomeBack: "Welcome back!",
    accountCreated: "Account created!",
    redirectingToHubb: "Redirecting to .Hubb...",
    signedInWithGoogle: "Signed in with Google",
    away: "away",
    // Profile Dialog
    profileTitle: "Your Profile",
    profileDesc: "Manage your account settings and preferences",
    displayName: "Display Name",
    enterDisplayName: "Enter your display name",
    username: "Username",
    enterUsername: "Enter your username",
    usernameEmpty: "Username cannot be empty",
    profileUpdated: "Profile updated",
    profileUpdatedDesc: "Your changes have been saved",
    profilePictureUpdated: "Profile picture updated",
    accountType: "Account Type",
    user: "User",
    business: "Business",
    dataSharing: "Data Sharing",
    dataSharingEnabled: "Enabled",
    editProfile: "Edit Profile",
    saveChanges: "Save Changes",
    close: "Close",
    // Help Dialog
    helpTitle: "Help & Support",
    helpDesc: "Report issues or send feedback to help us improve",
    whatTypeIssue: "What type of issue?",
    bug: "Bug",
    bugDesc: "Something isn't working",
    feedback: "Feedback",
    feedbackDesc: "Share your thoughts",
    wrongData: "Wrong Data",
    wrongDataDesc: "Incorrect information",
    tellUsMore: "Tell us more",
    describeIssue: "Describe the issue in detail...",
    attachScreenshot: "Attach Screenshot (optional)",
    clickToUpload: "Click to upload an image",
    fileTooLarge: "File too large",
    fileUnder5MB: "Please select a file under 5MB",
    selectIssueType: "Please select an issue type",
    describeTheIssue: "Please describe the issue",
    reportSubmitted: "Report submitted!",
    thankYouFeedback: "Thank you for your feedback",
    submitting: "Submitting...",
    submitReport: "Submit Report",
    // Time of day
    morning: "Morning",
    afternoon: "Afternoon",
    evening: "Evening",
    lateAfternoon: "Late Afternoon",
    // Cuisines
    thai: "Thai",
    isan: "Isan",
    chinese: "Chinese",
    japanese: "Japanese",
    korean: "Korean",
    seafood: "Seafood",
    noodles: "Noodles",
    western: "Western",
    indian: "Indian",
    vietnamese: "Vietnamese",
    cafe: "Cafe",
    streetFood: "Street Food",
    bbq: "BBQ",
    fusion: "Fusion",
    northern: "Northern",
    southern: "Southern",
  },
  th: {
    chat: "แชท",
    itinerary: "แผนการเดินทาง",
    landmark: "สถานที่น่าสนใจ",
    polaroid: "โพลารอยด์",
    profile: "โปรไฟล์",
    help: "ช่วยเหลือ",
    signOut: "ออกจากระบบ",
    newChat: "แชทใหม่",
    searchPlaceholder: "ค้นหาสถานที่...",
    startNavigation: "เริ่มนำทาง",
    pause: "หยุด",
    walk: "เดิน",
    drive: "ขับรถ",
    transit: "ขนส่งสาธารณะ",
    showSteps: "แสดงขั้นตอน",
    hideSteps: "ซ่อนขั้นตอน",
    locateMe: "หาตำแหน่งของฉัน",
    arrived: "คุณมาถึงแล้ว!",
    welcomeTo: "ยินดีต้อนรับสู่",
    routeError: "ไม่สามารถคำนวณเส้นทางได้",
    locationFound: "พบตำแหน่งแล้ว",
    usingCurrentLocation: "ใช้ตำแหน่งปัจจุบันของคุณ",
    findRestaurant: "หาร้านอาหารให้หน่อย",
    cheapEats: "อาหารราคาถูกใกล้เคียง",
    premiumSeafood: "อาหารทะเลพรีเมียม",
    spicyFood: "อาหารรสเผ็ด",
    lateNightFood: "อาหารดึก",
    minWait: "นาที รอ",
    viewOnMap: "ดูบนแผนที่",
    directions: "เส้นทาง",
    all: "ทั้งหมด",
    highestRated: "คะแนนสูงสุด",
    mostReviews: "รีวิวมากสุด",
    landmarksFound: "สถานที่พบ",
    bestTime: "เวลาที่ดี",
    estimatedTime: "~",
    modes: "โหมด",
    recentChats: "แชทล่าสุด",
    noRecentChats: "ไม่มีแชทล่าสุด",
    pressNewChat: "กด \"+ แชทใหม่\" เพื่อเริ่มต้น!",
    deleteChat: "ลบแชทนี้?",
    deleteChatDesc: "การกระทำนี้ไม่สามารถย้อนกลับได้ แชทนี้และข้อความทั้งหมดจะถูกลบถาวร",
    cancel: "ยกเลิก",
    delete: "ลบ",
    startConversation: "เริ่มการสนทนา",
    startConversationDesc: "ถามฉันเกี่ยวกับร้านอาหาร เวลารอคิว หรือคำแนะนำท้องถิ่น!",
    planAdventure: "วางแผนการผจญภัย",
    planAdventureDesc: "บอกงบประมาณและความสนใจของคุณ ฉันจะสร้างแผนการเดินทางที่สมบูรณ์แบบ",
    discoverLandmarks: "ค้นพบสถานที่น่าสนใจ",
    discoverLandmarksDesc: "ค้นหาจุดถ่ายรูปสวยๆ และสถานที่ซ่อนเร้นในบรรทัดทอง",
    createPolaroids: "สร้างโพลารอยด์",
    createPolaroidsDesc: "อัปโหลดรูปภาพของคุณ ฉันจะเปลี่ยนเป็นโพลารอยด์สวยๆ",
    messagePlaceholder: "ข้อความถึง .Hubb...",
    bantadthongDistrict: "เขตบรรทัดทอง",
    listening: "กำลังฟัง...",
    active: "ใช้งาน",
    chatMode: "แชท",
    itineraryMode: "โหมดแผนการเดินทาง",
    landmarkMode: "โหมดสถานที่น่าสนใจ",
    polaroidMode: "โหมดโพลารอยด์",
    today: "วันนี้",
    yesterday: "เมื่อวาน",
    daysAgo: "วันที่แล้ว",
    new: "ใหม่",
    noLandmarksFound: "ไม่พบสถานที่ตามเกณฑ์ของคุณ",
    university: "มหาวิทยาลัย",
    shopping: "ช้อปปิ้ง",
    museum: "พิพิธภัณฑ์",
    temple: "วัด",
    park: "สวนสาธารณะ",
    market: "ตลาด",
    // Prompt suggestions
    findRestaurantNoWait: "หาร้านอาหารที่ไม่ต้องรอคิว",
    bestCheapEats: "อาหารราคาถูกที่ดีที่สุดใกล้เคียง",
    somethingSpicy: "อะไรเผ็ดๆ",
    // Toast notifications
    locationNotSupported: "ไม่รองรับตำแหน่ง",
    browserNoGeolocation: "เบราว์เซอร์ของคุณไม่รองรับการระบุตำแหน่ง ใช้ศูนย์กลางบรรทัดทอง",
    locationFoundTitle: "📍 พบตำแหน่งแล้ว",
    accuracyLabel: "ความแม่นยำ",
    locationOutsideBantadthong: "ตำแหน่งอยู่นอกบรรทัดทอง",
    usingBantadthongCenter: "ใช้ศูนย์กลางบรรทัดทองเป็นตำแหน่งของคุณ",
    couldNotGetLocation: "ไม่สามารถรับตำแหน่งได้",
    enableLocationAccess: "ใช้ศูนย์กลางบรรทัดทอง กรุณาเปิดใช้งานการเข้าถึงตำแหน่ง",
    liveTrackingEnabled: "🔴 เปิดใช้งานการติดตามแบบเรียลไทม์",
    locationWillUpdate: "ตำแหน่งของคุณจะอัปเดตแบบเรียลไทม์",
    youveArrived: "🎉 คุณมาถึงแล้ว!",
    gpsError: "ข้อผิดพลาด GPS",
    couldNotUpdateLocation: "ไม่สามารถอัปเดตตำแหน่งได้ กำลังลองใหม่...",
    liveTrackingStopped: "หยุดการติดตามแบบเรียลไทม์",
    locationNoLongerTracked: "ตำแหน่งของคุณไม่ถูกติดตามอีกต่อไป",
    // Review notifications
    justReviewed: "เพิ่งรีวิว",
    justVisited: "เพิ่งไปเยือน",
    minutesAgo: "นาทีที่แล้ว",
    leftReviewAt: "ให้รีวิวที่",
    justNow: "เมื่อกี้",
    // Itinerary
    itineraryPlanner: "วางแผนการเดินทาง 🗺️",
    planBantadthongTour: "วางแผนทัวร์อาหารบรรทัดทองที่สมบูรณ์แบบ",
    budgetLevel: "ระดับงบประมาณ",
    budgetLow: "฿ ประหยัด",
    budgetMid: "฿฿ กลาง",
    budgetHigh: "฿฿฿ พรีเมียม",
    underPrice: "ต่ำกว่า 400 บาท",
    midPrice: "400-700 บาท",
    highPrice: "700+ บาท",
    numberOfPlaces: "จำนวนสถานที่",
    cuisinePreference: "ประเภทอาหารที่ชอบ",
    anyCuisine: "อาหารทุกประเภท",
    generateItinerary: "สร้างแผนการเดินทาง",
    estBudget: "งบประมาณโดยประมาณ",
    totalWait: "เวลารอรวม",
    stops: "จุดแวะ",
    editPreferences: "แก้ไขการตั้งค่า",
    // Polaroid
    polaroidModeTitle: "โหมดโพลารอยด์ 📸",
    transformMemories: "เปลี่ยนความทรงจำบรรทัดทองของคุณเป็นโพลารอยด์วินเทจ",
    uploadPhoto: "อัปโหลดรูปภาพ",
    clickOrDrag: "คลิกหรือลากและวาง",
    createPolaroidBtn: "สร้างโพลารอยด์",
    creating: "กำลังสร้าง...",
    download: "ดาวน์โหลด",
    polaroidCreated: "สร้างโพลารอยด์แล้ว! 📸",
    photoTransformed: "รูปภาพของคุณถูกเปลี่ยนเป็นโพลารอยด์แล้ว",
    downloaded: "ดาวน์โหลดแล้ว!",
    polaroidSaved: "โพลารอยด์ของคุณถูกบันทึกแล้ว",
    // Auth & Logout
    signedOut: "ออกจากระบบแล้ว",
    seeYouNextTime: "แล้วพบกันใหม่!",
    welcomeBack: "ยินดีต้อนรับกลับ!",
    accountCreated: "สร้างบัญชีแล้ว!",
    redirectingToHubb: "กำลังเปลี่ยนเส้นทางไปยัง .Hubb...",
    signedInWithGoogle: "เข้าสู่ระบบด้วย Google",
    away: "ห่างออกไป",
    // Profile Dialog
    profileTitle: "โปรไฟล์ของคุณ",
    profileDesc: "จัดการการตั้งค่าบัญชีและการตั้งค่าของคุณ",
    displayName: "ชื่อที่แสดง",
    enterDisplayName: "ใส่ชื่อที่แสดงของคุณ",
    username: "ชื่อผู้ใช้",
    enterUsername: "ใส่ชื่อผู้ใช้ของคุณ",
    usernameEmpty: "ชื่อผู้ใช้ไม่สามารถว่างได้",
    profileUpdated: "อัปเดตโปรไฟล์แล้ว",
    profileUpdatedDesc: "การเปลี่ยนแปลงของคุณถูกบันทึกแล้ว",
    profilePictureUpdated: "อัปเดตรูปโปรไฟล์แล้ว",
    accountType: "ประเภทบัญชี",
    user: "ผู้ใช้",
    business: "ธุรกิจ",
    dataSharing: "การแชร์ข้อมูล",
    dataSharingEnabled: "เปิดใช้งาน",
    editProfile: "แก้ไขโปรไฟล์",
    saveChanges: "บันทึกการเปลี่ยนแปลง",
    close: "ปิด",
    // Help Dialog
    helpTitle: "ช่วยเหลือและสนับสนุน",
    helpDesc: "รายงานปัญหาหรือส่งความคิดเห็นเพื่อช่วยเราปรับปรุง",
    whatTypeIssue: "ประเภทของปัญหาคืออะไร?",
    bug: "บัก",
    bugDesc: "มีบางอย่างไม่ทำงาน",
    feedback: "ความคิดเห็น",
    feedbackDesc: "แบ่งปันความคิดเห็นของคุณ",
    wrongData: "ข้อมูลผิด",
    wrongDataDesc: "ข้อมูลไม่ถูกต้อง",
    tellUsMore: "บอกเราเพิ่มเติม",
    describeIssue: "อธิบายปัญหาอย่างละเอียด...",
    attachScreenshot: "แนบภาพหน้าจอ (ถ้ามี)",
    clickToUpload: "คลิกเพื่ออัปโหลดรูปภาพ",
    fileTooLarge: "ไฟล์ใหญ่เกินไป",
    fileUnder5MB: "กรุณาเลือกไฟล์ที่มีขนาดต่ำกว่า 5MB",
    selectIssueType: "กรุณาเลือกประเภทปัญหา",
    describeTheIssue: "กรุณาอธิบายปัญหา",
    reportSubmitted: "ส่งรายงานแล้ว!",
    thankYouFeedback: "ขอบคุณสำหรับความคิดเห็นของคุณ",
    submitting: "กำลังส่ง...",
    submitReport: "ส่งรายงาน",
    // Time of day
    morning: "เช้า",
    afternoon: "บ่าย",
    evening: "เย็น",
    lateAfternoon: "บ่ายแก่",
    // Cuisines
    thai: "ไทย",
    isan: "อีสาน",
    chinese: "จีน",
    japanese: "ญี่ปุ่น",
    korean: "เกาหลี",
    seafood: "อาหารทะเล",
    noodles: "ก๋วยเตี๋ยว",
    western: "ตะวันตก",
    indian: "อินเดีย",
    vietnamese: "เวียดนาม",
    cafe: "คาเฟ่",
    streetFood: "อาหารข้างทาง",
    bbq: "บาร์บีคิว",
    fusion: "ฟิวชั่น",
    northern: "ภาคเหนือ",
    southern: "ภาคใต้",
  },
  zh: {
    chat: "聊天",
    itinerary: "行程",
    landmark: "地标",
    polaroid: "拍立得",
    profile: "个人资料",
    help: "帮助与支持",
    signOut: "退出",
    newChat: "新聊天",
    searchPlaceholder: "搜索地标...",
    startNavigation: "开始导航",
    pause: "暂停",
    walk: "步行",
    drive: "驾车",
    transit: "公交",
    showSteps: "显示步骤",
    hideSteps: "隐藏步骤",
    locateMe: "定位我",
    arrived: "您已到达！",
    welcomeTo: "欢迎来到",
    routeError: "无法计算路线",
    locationFound: "已找到位置",
    usingCurrentLocation: "使用您的当前位置",
    findRestaurant: "帮我找餐厅",
    cheapEats: "附近便宜美食",
    premiumSeafood: "高级海鲜",
    spicyFood: "辣味美食",
    lateNightFood: "宵夜",
    minWait: "分钟等待",
    viewOnMap: "在地图上查看",
    directions: "路线",
    all: "全部",
    highestRated: "评分最高",
    mostReviews: "评论最多",
    landmarksFound: "个地标",
    bestTime: "最佳",
    estimatedTime: "约",
    modes: "模式",
    recentChats: "最近聊天",
    noRecentChats: "没有最近的聊天",
    pressNewChat: "点击\"+ 新聊天\"开始！",
    deleteChat: "删除此聊天？",
    deleteChatDesc: "此操作无法撤销。这将永久删除此聊天会话及其所有消息。",
    cancel: "取消",
    delete: "删除",
    startConversation: "开始对话",
    startConversationDesc: "询问我关于餐厅、排队时间或当地推荐！",
    planAdventure: "规划您的冒险",
    planAdventureDesc: "告诉我您的预算和兴趣，我将为您创建完美的行程。",
    discoverLandmarks: "发现地标",
    discoverLandmarksDesc: "找到适合拍照的地点和班塔通的隐藏宝石。",
    createPolaroids: "创建拍立得",
    createPolaroidsDesc: "上传您的照片，我将把它们变成美丽的拍立得。",
    messagePlaceholder: "给 .Hubb 发消息...",
    bantadthongDistrict: "班塔通区",
    listening: "正在听...",
    active: "活跃",
    chatMode: "聊天",
    itineraryMode: "行程模式",
    landmarkMode: "地标模式",
    polaroidMode: "拍立得模式",
    today: "今天",
    yesterday: "昨天",
    daysAgo: "天前",
    new: "新",
    noLandmarksFound: "没有找到符合条件的地标。",
    university: "大学",
    shopping: "购物",
    museum: "博物馆",
    temple: "寺庙",
    park: "公园",
    market: "市场",
    // Prompt suggestions
    findRestaurantNoWait: "帮我找不用排队的餐厅",
    bestCheapEats: "附近最好的便宜美食",
    somethingSpicy: "辣的东西",
    // Toast notifications
    locationNotSupported: "不支持定位",
    browserNoGeolocation: "您的浏览器不支持地理定位。使用班塔通中心。",
    locationFoundTitle: "📍 已找到位置",
    accuracyLabel: "精度",
    locationOutsideBantadthong: "位置在班塔通外",
    usingBantadthongCenter: "使用班塔通中心作为您的位置",
    couldNotGetLocation: "无法获取位置",
    enableLocationAccess: "使用班塔通中心。请启用位置访问。",
    liveTrackingEnabled: "🔴 实时追踪已启用",
    locationWillUpdate: "您的位置将实时更新",
    youveArrived: "🎉 您已到达！",
    gpsError: "GPS 错误",
    couldNotUpdateLocation: "无法更新位置。正在重试...",
    liveTrackingStopped: "实时追踪已停止",
    locationNoLongerTracked: "您的位置不再被追踪",
    // Review notifications
    justReviewed: "刚刚评价了",
    justVisited: "刚刚访问了",
    minutesAgo: "分钟前",
    leftReviewAt: "给...留下评价",
    justNow: "刚刚",
    // Itinerary
    itineraryPlanner: "行程规划 🗺️",
    planBantadthongTour: "规划您完美的班塔通美食之旅",
    budgetLevel: "预算级别",
    budgetLow: "฿ 经济",
    budgetMid: "฿฿ 中等",
    budgetHigh: "฿฿฿ 高端",
    underPrice: "400泰铢以下",
    midPrice: "400-700泰铢",
    highPrice: "700+泰铢",
    numberOfPlaces: "地点数量",
    cuisinePreference: "菜系偏好",
    anyCuisine: "任何菜系",
    generateItinerary: "生成行程",
    estBudget: "预估预算",
    totalWait: "总等待时间",
    stops: "停靠点",
    editPreferences: "编辑偏好",
    // Polaroid
    polaroidModeTitle: "拍立得模式 📸",
    transformMemories: "将您的班塔通回忆转化为复古拍立得",
    uploadPhoto: "上传照片",
    clickOrDrag: "点击或拖放",
    createPolaroidBtn: "创建拍立得",
    creating: "创建中...",
    download: "下载",
    polaroidCreated: "拍立得已创建！📸",
    photoTransformed: "您的照片已转化为拍立得。",
    downloaded: "已下载！",
    polaroidSaved: "您的拍立得已保存。",
    // Auth & Logout
    signedOut: "已退出",
    seeYouNextTime: "下次见！",
    welcomeBack: "欢迎回来！",
    accountCreated: "账户已创建！",
    redirectingToHubb: "正在跳转到 .Hubb...",
    signedInWithGoogle: "已使用Google登录",
    away: "远",
    // Profile Dialog
    profileTitle: "您的个人资料",
    profileDesc: "管理您的账户设置和偏好",
    displayName: "显示名称",
    enterDisplayName: "输入您的显示名称",
    username: "用户名",
    enterUsername: "输入您的用户名",
    usernameEmpty: "用户名不能为空",
    profileUpdated: "个人资料已更新",
    profileUpdatedDesc: "您的更改已保存",
    profilePictureUpdated: "头像已更新",
    accountType: "账户类型",
    user: "用户",
    business: "商家",
    dataSharing: "数据共享",
    dataSharingEnabled: "已启用",
    editProfile: "编辑资料",
    saveChanges: "保存更改",
    close: "关闭",
    // Help Dialog
    helpTitle: "帮助与支持",
    helpDesc: "报告问题或发送反馈帮助我们改进",
    whatTypeIssue: "问题类型是什么？",
    bug: "错误",
    bugDesc: "有些功能不正常",
    feedback: "反馈",
    feedbackDesc: "分享您的想法",
    wrongData: "数据错误",
    wrongDataDesc: "信息不正确",
    tellUsMore: "告诉我们更多",
    describeIssue: "详细描述问题...",
    attachScreenshot: "附加截图（可选）",
    clickToUpload: "点击上传图片",
    fileTooLarge: "文件太大",
    fileUnder5MB: "请选择小于5MB的文件",
    selectIssueType: "请选择问题类型",
    describeTheIssue: "请描述问题",
    reportSubmitted: "报告已提交！",
    thankYouFeedback: "感谢您的反馈",
    submitting: "提交中...",
    submitReport: "提交报告",
    // Time of day
    morning: "上午",
    afternoon: "下午",
    evening: "傍晚",
    lateAfternoon: "午后",
    // Cuisines
    thai: "泰式",
    isan: "伊森",
    chinese: "中式",
    japanese: "日式",
    korean: "韩式",
    seafood: "海鲜",
    noodles: "面条",
    western: "西式",
    indian: "印度",
    vietnamese: "越南",
    cafe: "咖啡厅",
    streetFood: "街头小吃",
    bbq: "烧烤",
    fusion: "融合",
    northern: "北方",
    southern: "南方",
  },
  ja: {
    chat: "チャット",
    itinerary: "旅程",
    landmark: "ランドマーク",
    polaroid: "ポラロイド",
    profile: "プロフィール",
    help: "ヘルプ",
    signOut: "ログアウト",
    newChat: "新しいチャット",
    searchPlaceholder: "ランドマークを検索...",
    startNavigation: "ナビ開始",
    pause: "一時停止",
    walk: "徒歩",
    drive: "車",
    transit: "公共交通",
    showSteps: "ステップを表示",
    hideSteps: "ステップを隠す",
    locateMe: "現在地を取得",
    arrived: "到着しました！",
    welcomeTo: "ようこそ",
    routeError: "ルートを計算できません",
    locationFound: "位置が見つかりました",
    usingCurrentLocation: "現在地を使用しています",
    findRestaurant: "レストランを探して",
    cheapEats: "近くの安い料理",
    premiumSeafood: "高級シーフード",
    spicyFood: "辛い料理",
    lateNightFood: "深夜グルメ",
    minWait: "分待ち",
    viewOnMap: "地図で見る",
    directions: "ルート案内",
    all: "すべて",
    highestRated: "評価順",
    mostReviews: "レビュー順",
    landmarksFound: "件のランドマーク",
    bestTime: "最適",
    estimatedTime: "約",
    modes: "モード",
    recentChats: "最近のチャット",
    noRecentChats: "最近のチャットはありません",
    pressNewChat: "\"+ 新しいチャット\"を押して開始！",
    deleteChat: "このチャットを削除しますか？",
    deleteChatDesc: "この操作は元に戻せません。このチャットセッションとすべてのメッセージが完全に削除されます。",
    cancel: "キャンセル",
    delete: "削除",
    startConversation: "会話を始める",
    startConversationDesc: "レストラン、待ち時間、地元のおすすめについて聞いてください！",
    planAdventure: "冒険を計画",
    planAdventureDesc: "予算と興味を教えてください。完璧な旅程を作成します。",
    discoverLandmarks: "ランドマークを発見",
    discoverLandmarksDesc: "バンタトンのインスタ映えスポットと隠れた名所を見つけよう。",
    createPolaroids: "ポラロイドを作成",
    createPolaroidsDesc: "写真をアップロードすると、美しいポラロイドに変換します。",
    messagePlaceholder: ".Hubb にメッセージ...",
    bantadthongDistrict: "バンタトン地区",
    listening: "聞いています...",
    active: "アクティブ",
    chatMode: "チャット",
    itineraryMode: "旅程モード",
    landmarkMode: "ランドマークモード",
    polaroidMode: "ポラロイドモード",
    today: "今日",
    yesterday: "昨日",
    daysAgo: "日前",
    new: "新規",
    noLandmarksFound: "条件に一致するランドマークが見つかりません。",
    university: "大学",
    shopping: "ショッピング",
    museum: "博物館",
    temple: "寺院",
    park: "公園",
    market: "市場",
    // Prompt suggestions
    findRestaurantNoWait: "待ち時間なしのレストランを探して",
    bestCheapEats: "近くで一番お得なグルメ",
    somethingSpicy: "辛いもの",
    // Toast notifications
    locationNotSupported: "位置情報非対応",
    browserNoGeolocation: "お使いのブラウザは位置情報をサポートしていません。バンタトン中心を使用します。",
    locationFoundTitle: "📍 位置が見つかりました",
    accuracyLabel: "精度",
    locationOutsideBantadthong: "バンタトン外の位置",
    usingBantadthongCenter: "バンタトン中心を現在地として使用",
    couldNotGetLocation: "位置を取得できませんでした",
    enableLocationAccess: "バンタトン中心を使用。位置情報へのアクセスを有効にしてください。",
    liveTrackingEnabled: "🔴 リアルタイム追跡有効",
    locationWillUpdate: "位置情報がリアルタイムで更新されます",
    youveArrived: "🎉 到着しました！",
    gpsError: "GPS エラー",
    couldNotUpdateLocation: "位置を更新できませんでした。再試行中...",
    liveTrackingStopped: "リアルタイム追跡停止",
    locationNoLongerTracked: "位置情報の追跡が停止されました",
    // Review notifications
    justReviewed: "がレビューしました",
    justVisited: "が訪問しました",
    minutesAgo: "分前",
    leftReviewAt: "にレビューを残しました",
    justNow: "たった今",
    // Itinerary
    itineraryPlanner: "旅程プランナー 🗺️",
    planBantadthongTour: "完璧なバンタトンフードツアーを計画",
    budgetLevel: "予算レベル",
    budgetLow: "฿ お手頃",
    budgetMid: "฿฿ 中程度",
    budgetHigh: "฿฿฿ プレミアム",
    underPrice: "400バーツ以下",
    midPrice: "400-700バーツ",
    highPrice: "700+バーツ",
    numberOfPlaces: "場所の数",
    cuisinePreference: "料理の好み",
    anyCuisine: "すべての料理",
    generateItinerary: "旅程を生成",
    estBudget: "推定予算",
    totalWait: "合計待ち時間",
    stops: "停車地",
    editPreferences: "設定を編集",
    // Polaroid
    polaroidModeTitle: "ポラロイドモード 📸",
    transformMemories: "バンタトンの思い出をビンテージポラロイドに変換",
    uploadPhoto: "写真をアップロード",
    clickOrDrag: "クリックまたはドラッグ＆ドロップ",
    createPolaroidBtn: "ポラロイドを作成",
    creating: "作成中...",
    download: "ダウンロード",
    polaroidCreated: "ポラロイド作成完了！📸",
    photoTransformed: "写真がポラロイドに変換されました。",
    downloaded: "ダウンロード完了！",
    polaroidSaved: "ポラロイドが保存されました。",
    // Auth & Logout
    signedOut: "ログアウトしました",
    seeYouNextTime: "また会いましょう！",
    welcomeBack: "おかえりなさい！",
    accountCreated: "アカウント作成完了！",
    redirectingToHubb: ".Hubb にリダイレクト中...",
    signedInWithGoogle: "Googleでログインしました",
    away: "離れ",
    // Profile Dialog
    profileTitle: "プロフィール",
    profileDesc: "アカウント設定と環境設定を管理",
    displayName: "表示名",
    enterDisplayName: "表示名を入力",
    username: "ユーザー名",
    enterUsername: "ユーザー名を入力",
    usernameEmpty: "ユーザー名は空にできません",
    profileUpdated: "プロフィール更新完了",
    profileUpdatedDesc: "変更が保存されました",
    profilePictureUpdated: "プロフィール画像を更新しました",
    accountType: "アカウントタイプ",
    user: "ユーザー",
    business: "ビジネス",
    dataSharing: "データ共有",
    dataSharingEnabled: "有効",
    editProfile: "プロフィールを編集",
    saveChanges: "変更を保存",
    close: "閉じる",
    // Help Dialog
    helpTitle: "ヘルプ＆サポート",
    helpDesc: "問題を報告したりフィードバックを送信して改善にご協力ください",
    whatTypeIssue: "問題の種類は？",
    bug: "バグ",
    bugDesc: "何か動作しない",
    feedback: "フィードバック",
    feedbackDesc: "ご意見を共有",
    wrongData: "データエラー",
    wrongDataDesc: "情報が正しくない",
    tellUsMore: "詳しく教えてください",
    describeIssue: "問題を詳しく説明してください...",
    attachScreenshot: "スクリーンショットを添付（任意）",
    clickToUpload: "クリックして画像をアップロード",
    fileTooLarge: "ファイルが大きすぎます",
    fileUnder5MB: "5MB未満のファイルを選択してください",
    selectIssueType: "問題の種類を選択してください",
    describeTheIssue: "問題を説明してください",
    reportSubmitted: "レポートを送信しました！",
    thankYouFeedback: "フィードバックありがとうございます",
    submitting: "送信中...",
    submitReport: "レポートを送信",
    // Time of day
    morning: "朝",
    afternoon: "午後",
    evening: "夕方",
    lateAfternoon: "夕方前",
    // Cuisines
    thai: "タイ",
    isan: "イサーン",
    chinese: "中華",
    japanese: "和食",
    korean: "韓国",
    seafood: "シーフード",
    noodles: "麺類",
    western: "洋食",
    indian: "インド",
    vietnamese: "ベトナム",
    cafe: "カフェ",
    streetFood: "屋台",
    bbq: "焼肉",
    fusion: "フュージョン",
    northern: "北部",
    southern: "南部",
  },
  ko: {
    chat: "채팅",
    itinerary: "일정",
    landmark: "랜드마크",
    polaroid: "폴라로이드",
    profile: "프로필",
    help: "도움말",
    signOut: "로그아웃",
    newChat: "새 채팅",
    searchPlaceholder: "랜드마크 검색...",
    startNavigation: "길안내 시작",
    pause: "일시정지",
    walk: "도보",
    drive: "자동차",
    transit: "대중교통",
    showSteps: "단계 표시",
    hideSteps: "단계 숨기기",
    locateMe: "내 위치 찾기",
    arrived: "도착했습니다!",
    welcomeTo: "환영합니다",
    routeError: "경로를 계산할 수 없습니다",
    locationFound: "위치를 찾았습니다",
    usingCurrentLocation: "현재 위치 사용 중",
    findRestaurant: "레스토랑 찾기",
    cheapEats: "근처 저렴한 음식",
    premiumSeafood: "프리미엄 해산물",
    spicyFood: "매운 음식",
    lateNightFood: "야식",
    minWait: "분 대기",
    viewOnMap: "지도에서 보기",
    directions: "길찾기",
    all: "전체",
    highestRated: "평점순",
    mostReviews: "리뷰순",
    landmarksFound: "개 랜드마크",
    bestTime: "최적",
    estimatedTime: "약",
    modes: "모드",
    recentChats: "최근 채팅",
    noRecentChats: "최근 채팅이 없습니다",
    pressNewChat: "\"+ 새 채팅\"을 눌러 시작하세요!",
    deleteChat: "이 채팅을 삭제하시겠습니까?",
    deleteChatDesc: "이 작업은 되돌릴 수 없습니다. 이 채팅 세션과 모든 메시지가 영구적으로 삭제됩니다.",
    cancel: "취소",
    delete: "삭제",
    startConversation: "대화 시작",
    startConversationDesc: "레스토랑, 대기 시간 또는 현지 추천에 대해 물어보세요!",
    planAdventure: "모험 계획",
    planAdventureDesc: "예산과 관심사를 알려주시면 완벽한 일정을 만들어 드립니다.",
    discoverLandmarks: "랜드마크 발견",
    discoverLandmarksDesc: "반타통의 인스타그램용 명소와 숨겨진 보석을 찾아보세요.",
    createPolaroids: "폴라로이드 만들기",
    createPolaroidsDesc: "사진을 업로드하면 아름다운 폴라로이드로 변환해 드립니다.",
    messagePlaceholder: ".Hubb에 메시지...",
    bantadthongDistrict: "반타통 지구",
    listening: "듣는 중...",
    active: "활성",
    chatMode: "채팅",
    itineraryMode: "일정 모드",
    landmarkMode: "랜드마크 모드",
    polaroidMode: "폴라로이드 모드",
    today: "오늘",
    yesterday: "어제",
    daysAgo: "일 전",
    new: "새로운",
    noLandmarksFound: "조건에 맞는 랜드마크가 없습니다.",
    university: "대학교",
    shopping: "쇼핑",
    museum: "박물관",
    temple: "사원",
    park: "공원",
    market: "시장",
    // Prompt suggestions
    findRestaurantNoWait: "대기 없는 레스토랑 찾기",
    bestCheapEats: "근처 최고의 저렴한 맛집",
    somethingSpicy: "매운 것",
    // Toast notifications
    locationNotSupported: "위치 미지원",
    browserNoGeolocation: "브라우저가 위치 정보를 지원하지 않습니다. 반타통 중심을 사용합니다.",
    locationFoundTitle: "📍 위치를 찾았습니다",
    accuracyLabel: "정확도",
    locationOutsideBantadthong: "반타통 외부 위치",
    usingBantadthongCenter: "반타통 중심을 현재 위치로 사용",
    couldNotGetLocation: "위치를 가져올 수 없습니다",
    enableLocationAccess: "반타통 중심 사용 중. 위치 접근을 활성화해 주세요.",
    liveTrackingEnabled: "🔴 실시간 추적 활성화",
    locationWillUpdate: "위치가 실시간으로 업데이트됩니다",
    youveArrived: "🎉 도착했습니다!",
    gpsError: "GPS 오류",
    couldNotUpdateLocation: "위치를 업데이트할 수 없습니다. 재시도 중...",
    liveTrackingStopped: "실시간 추적 중지",
    locationNoLongerTracked: "더 이상 위치가 추적되지 않습니다",
    // Review notifications
    justReviewed: "님이 리뷰했습니다",
    justVisited: "님이 방문했습니다",
    minutesAgo: "분 전",
    leftReviewAt: "에 리뷰를 남겼습니다",
    justNow: "방금",
    // Itinerary
    itineraryPlanner: "일정 플래너 🗺️",
    planBantadthongTour: "완벽한 반타통 푸드 투어를 계획하세요",
    budgetLevel: "예산 수준",
    budgetLow: "฿ 저렴",
    budgetMid: "฿฿ 중간",
    budgetHigh: "฿฿฿ 프리미엄",
    underPrice: "400바트 이하",
    midPrice: "400-700바트",
    highPrice: "700+바트",
    numberOfPlaces: "장소 수",
    cuisinePreference: "요리 선호도",
    anyCuisine: "모든 요리",
    generateItinerary: "일정 생성",
    estBudget: "예상 예산",
    totalWait: "총 대기 시간",
    stops: "정거장",
    editPreferences: "설정 편집",
    // Polaroid
    polaroidModeTitle: "폴라로이드 모드 📸",
    transformMemories: "반타통의 추억을 빈티지 폴라로이드로 변환",
    uploadPhoto: "사진 업로드",
    clickOrDrag: "클릭하거나 끌어다 놓기",
    createPolaroidBtn: "폴라로이드 만들기",
    creating: "만드는 중...",
    download: "다운로드",
    polaroidCreated: "폴라로이드 생성 완료! 📸",
    photoTransformed: "사진이 폴라로이드로 변환되었습니다.",
    downloaded: "다운로드 완료!",
    polaroidSaved: "폴라로이드가 저장되었습니다.",
    // Auth & Logout
    signedOut: "로그아웃됨",
    seeYouNextTime: "다음에 만나요!",
    welcomeBack: "다시 오셨군요!",
    accountCreated: "계정이 생성되었습니다!",
    redirectingToHubb: ".Hubb으로 이동 중...",
    signedInWithGoogle: "Google로 로그인함",
    away: "떨어짐",
    // Profile Dialog
    profileTitle: "내 프로필",
    profileDesc: "계정 설정 및 환경설정 관리",
    displayName: "표시 이름",
    enterDisplayName: "표시 이름 입력",
    username: "사용자 이름",
    enterUsername: "사용자 이름 입력",
    usernameEmpty: "사용자 이름은 비워둘 수 없습니다",
    profileUpdated: "프로필 업데이트됨",
    profileUpdatedDesc: "변경사항이 저장되었습니다",
    profilePictureUpdated: "프로필 사진이 업데이트되었습니다",
    accountType: "계정 유형",
    user: "사용자",
    business: "비즈니스",
    dataSharing: "데이터 공유",
    dataSharingEnabled: "활성화됨",
    editProfile: "프로필 편집",
    saveChanges: "변경사항 저장",
    close: "닫기",
    // Help Dialog
    helpTitle: "도움말 및 지원",
    helpDesc: "문제를 보고하거나 피드백을 보내 개선에 도움을 주세요",
    whatTypeIssue: "문제 유형은?",
    bug: "버그",
    bugDesc: "뭔가 작동하지 않음",
    feedback: "피드백",
    feedbackDesc: "생각을 공유해주세요",
    wrongData: "잘못된 데이터",
    wrongDataDesc: "정보가 정확하지 않음",
    tellUsMore: "자세히 알려주세요",
    describeIssue: "문제를 자세히 설명해주세요...",
    attachScreenshot: "스크린샷 첨부 (선택사항)",
    clickToUpload: "클릭하여 이미지 업로드",
    fileTooLarge: "파일이 너무 큽니다",
    fileUnder5MB: "5MB 미만의 파일을 선택해주세요",
    selectIssueType: "문제 유형을 선택해주세요",
    describeTheIssue: "문제를 설명해주세요",
    reportSubmitted: "보고서가 제출되었습니다!",
    thankYouFeedback: "피드백 감사합니다",
    submitting: "제출 중...",
    submitReport: "보고서 제출",
    // Time of day
    morning: "아침",
    afternoon: "오후",
    evening: "저녁",
    lateAfternoon: "늦은 오후",
    // Cuisines
    thai: "태국",
    isan: "이산",
    chinese: "중식",
    japanese: "일식",
    korean: "한식",
    seafood: "해산물",
    noodles: "면류",
    western: "양식",
    indian: "인도",
    vietnamese: "베트남",
    cafe: "카페",
    streetFood: "길거리 음식",
    bbq: "바비큐",
    fusion: "퓨전",
    northern: "북부",
    southern: "남부",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  translateCuisine: (cuisine: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("hubb_language");
    return (saved as Language) || "en";
  });

  useEffect(() => {
    localStorage.setItem("hubb_language", language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  // Helper function to translate compound cuisines like "Thai-Chinese", "Chinese-Thai"
  const translateCuisine = (cuisine: string): string => {
    // Handle compound cuisines with hyphens or spaces
    const separators = ['-', ' '];
    for (const sep of separators) {
      if (cuisine.includes(sep)) {
        const parts = cuisine.split(sep);
        const translatedParts = parts.map(part => {
          const key = part.toLowerCase().trim();
          return translations[language][key] || translations.en[key] || part;
        });
        return translatedParts.join(sep === '-' ? '-' : ' ');
      }
    }
    // Single cuisine
    const key = cuisine.toLowerCase().trim();
    return translations[language][key] || translations.en[key] || cuisine;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, translateCuisine }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
